target 'round' do
  use_frameworks!
pod "EasyPeasy"
pod 'Kingfisher', '~> 5.0'
pod 'ZIPFoundation'
pod 'Firebase/Analytics'
pod 'Firebase/Crashlytics'
pod 'Firebase/Database'
pod 'Firebase/Functions'
pod 'Firebase/Core'
pod 'Firebase/Firestore'
pod 'Firebase/Auth'
pod 'Firebase/Storage'
pod 'CodableFirebase'
pod 'Gemini'
pod 'RealmSwift'
pod 'Purchases'
end
